Adds robot status publishing to Rapid driver
ros-industrial/abb pull request #145
Opened 2018-03-01 15:30 UTC by yamokosk

Continuation of #144. Fully tested on hardware and a packet capture is included to verify. In capture robot was commanded to move to a few points and at the end of the capture, the E-stop was pressed.

The PR also standardizes whitespace indentation. Spaces, as opposed to tabs, were used more often for indentation so I changed everything to spaces. They are in separate commits to better see the changes.

[robot_status_message.pcapng.zip](https://github.com/ros-industrial/abb/files/1771700/robot_status_message.pcapng.zip)

2018-04-10 08:27 UTC, gavanderhoorn commented
@Levi-Armstrong: is this something you'd pick up?

@yamokosk: my apologies for our late response, this is definitely something that is of great interest :+1:

2018-04-20 15:16 UTC, gonzalocasas commented
It looks good to me.

Is there anything I could do to speed up the merge of this PR? I can offer to test it on some of our hardware if that helps. (or if there's another way to contribute to make the process smoother/faster, please let me know).

2018-04-20 15:19 UTC, gavanderhoorn commented
Getting a second user to verify this on their hw would be good, yes.

If you would be willing to do that, it would be appreciated.

2018-04-20 18:52 UTC, gonzalocasas commented
Yes, sure, I will test this next week in our hardware and post here! Thx!

2018-05-05 15:11 UTC, gavanderhoorn commented
@gonzalocasas: have you had a chance to test this?

2018-05-05 16:25 UTC, gonzalocasas commented
@gavanderhoorn: preparations too a bit longer than expected, but I've scheduled the test for this Tuesday.

2018-05-07 15:35 UTC, gonzalocasas commented
@yamokosk is this how the signals should be configured?

![image](https://user-images.githubusercontent.com/933277/39710347-deec536a-521c-11e8-8d5c-72841a221a1b.png)

(In general, if a PR requires config changes, I'd suggest to include them as part of the description, so testing/review and transfer to the wiki is unambiguous).

2018-05-08 11:56 UTC, gonzalocasas commented
Ok, this seems to work.
I am still not sure if the signal configuration that I used is correct, but the `robot_status` looks like properly reflecting it, so lgtm.

2018-05-08 12:23 UTC, gavanderhoorn commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
It's been a while for me: are there no errors with `ERRNO > 90`?

2018-05-08 12:25 UTC, gavanderhoorn commented
Thanks for the check @gonzalocasas :+1: 

We'll have to make sure to document the signal configuration, as it's unclear right now, as you remark.

Ideally with both a comment at the top of the file as well as in the installation tutorial.

2018-05-08 14:12 UTC, gavanderhoorn commented
I actually believe `signalMotorOn` should be mapped to `Motors On State`, not `Motors On`.

2018-05-08 14:13 UTC, gavanderhoorn commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
Unless I'm misunderstanding something, errors can have nrs `> 90`, so this line may not be sufficient for detecting whether the system is in error or not.

2018-05-08 14:32 UTC, gonzalocasas commented
@gavanderhoorn it could be; but then it's unclear to me what's the correct mapping for `signalMotionPossible`.

2018-05-08 14:33 UTC, gavanderhoorn commented
Not sure either right now. Not near a robot/robotstudio/manual.

2018-05-08 14:38 UTC, gonzalocasas commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
I assume that comes out of the following description of `errnum` on RAPID reference:

![image](https://user-images.githubusercontent.com/933277/39763681-1d4708b4-52de-11e8-8dbb-2524bbd4b881.png)

2018-05-08 14:40 UTC, gavanderhoorn commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
Yes, I had understood that as well. But that bit of doc doesn't seem to limit error nrs to `[1, 90]` specifically.

2018-05-22 14:24 UTC, gonzalocasas commented
hi @yamokosk! could you pls give me a hand in describing how you configured the signals in your setup? I can then help with the documentation part so that this PR gets merged ;)

2018-05-22 16:39 UTC, gavanderhoorn commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
I'd forgotten about this: a knowledgable source has confirmed that error nrs can definitely be `> 90`, so this implementation is not sufficient to determine controller error status.

Most likely a combination of system outputs would be better.

2018-05-29 21:30 UTC, yamokosk commented
Hi guys, sorry for the delayed response. Sure. Do you want me to document how I created the signals in RobotStudio? I can send screenshots of the relevant screens if that works.

2018-05-30 04:30 UTC, gonzalocasas commented
@yamokosk yep, screenshots would help

2018-06-19 10:31 UTC, gavanderhoorn commented
@yamokosk: it would be great if we could include some documentation on how to setup everything needed wrt signals needed for this extension.

Could you provide the screenshot(s) that you offered?

2018-06-26 10:19 UTC, gavanderhoorn commented
@yamokosk: :bellhop_bell:

2018-08-01 09:28 UTC, gavanderhoorn commented
And another ping.

2018-10-17 15:28 UTC, keerthanamanivannan commented
Alright, I work with @yamokosk and I've been working on our robots with these changes. I'm attaching the screenshots that @yamokosk mentioned above. 

![pic1](https://user-images.githubusercontent.com/15019704/47097456-0bce5900-d1f7-11e8-8089-819b94572df9.png)
The above screenshot shows the place where we add these signals.

![pic2](https://user-images.githubusercontent.com/15019704/47097471-1983de80-d1f7-11e8-9c29-1a3dff2795d7.png)
And this one shows what System Outputs we tied the Signals to. 
Let me know if anything else is required!

2018-10-18 16:41 UTC, keerthanamanivannan commented
@gavanderhoorn @gonzalocasas ping.

2018-10-23 12:12 UTC, gavanderhoorn commented
> Let me know if anything else is required!

thanks for adding this @keerthanamanivannan.

It would be great if we could add this to either the readme of `abb_driver` and/or the [installation tutorial](http://wiki.ros.org/abb/Tutorials/InstallServer).

2018-10-24 16:07 UTC, keerthanamanivannan commented
@gavanderhoorn Sure, I can do that! 
How would I edit this link: [installation tutorial](http://wiki.ros.org/abb/Tutorials/InstallServer)?
It says that its an immutable page.

2018-10-24 16:10 UTC, keerthanamanivannan commented
@gavanderhoorn Sure, I can do that!
How would I edit this link: [nstallation tutorial](http://wiki.ros.org/abb/Tutorials/InstallServer)?
It says that its an immutable page.

2018-10-25 06:30 UTC, gavanderhoorn commented
Do you have a wiki account?

2018-10-25 13:02 UTC, keerthanamanivannan commented
Yes, I do.

2018-10-25 13:04 UTC, gavanderhoorn commented
And have you requested write access? That's a separate step.

If the answer is also "yes", then you should be able to open [this link](http://wiki.ros.org/action/edit/abb/Tutorials/InstallServer?action=edit&editor=text) and start editing.

2018-10-25 13:09 UTC, keerthanamanivannan commented
Oh. Well, no. I have never requested write access. How would I do that?

2018-10-25 13:58 UTC, gavanderhoorn commented
You can request that over in https://github.com/ros-infrastructure/roswiki/issues/258.

2018-10-31 15:21 UTC, gavanderhoorn commented
@keerthanamanivannan ?

2018-10-31 18:37 UTC, keerthanamanivannan commented
@gavanderhoorn I edited the abb InstallServer tutorial and clicked the save button and it got published! Thought it might go through some approval process of some sort, but yeah. Review that and change/modify it if necessary. Merge this PR. Let me know if anything else if required.

2018-11-01 10:18 UTC, gavanderhoorn commented
> I edited the abb InstallServer tutorial and clicked the save button and it got published!

great :) thanks.

> Thought it might go through some approval process of some sort, but yeah.

No, the wiki has no review process :)

> Review that and change/modify it if necessary. Merge this PR. Let me know if anything else is required.

Thanks for updating the docs.

I'll take a look at the PR, review your wiki changes and then merge.

2018-11-16 14:36 UTC, gavanderhoorn commented
@keerthanamanivannan @yamokosk: I've just tested this PR.

Basic functionality is ok: :+1: for that.

Three observations:

 - minor: robot status msgs are published at the same frequency as joint state msgs
 - robot `mode` is `-1` for me when the controller is in `OP_MAN_PROG` mode
 - `motion_possible` does not seem to take motor state or the state of `T_ROB1` into account: if I switch to `auto` mode, but motors are off, `motion_possible` is `1`. If I switch to `auto`, turn on the motors, but don't (re)start `T_ROB1`, `motion_possible` is also `1`. Without motor power or a running `T_ROB1` the robot will not move, so `motion_possible` should stay `0`

It's been a while since you submitted this PR, so would you still be up for fixing this?

@keerthanamanivannan: :+1: for updating the documentation. The instructions are clear and I encountered no issues following them.

2018-11-16 15:29 UTC, gavanderhoorn requested changes
@keerthanamanivannan @yamokosk: I've just tested this PR.

Basic functionality is ok: :+1: for that.

<del>Three</del> Five observations:

 - minor: robot status msgs are published at the same frequency as joint state msgs (something like 10 Hz would probably be enough)
 - robot `mode` is `-1` (ie: `UNKNOWN`) for me when the controller is in `OP_MAN_PROG` mode (should it be: `CASE OP_MAN_PROG, OP_MAN_TEST:`?)
 - `motion_possible` does not seem to take motor state or the state of `T_ROB1` into account: if I switch to `auto` mode, but motors are off, `motion_possible` is `1`. If I switch to `auto`, turn on the motors, but don't (re)start `T_ROB1`, `motion_possible` is also `1`. Without motor power or a running `T_ROB1` the robot will not move, so `motion_possible` should stay `0`
 - the switch statement mapping RAPID robot mode values to the ROS values does not check for `OP_UNDEF`
 - detection of error states does not seem sufficient (see inline comments on the PR)

It's been a while since you submitted this PR, so would you still be up for fixing this?

@keerthanamanivannan: :+1: for updating the documentation. The instructions are clear and I encountered no issues following them.

2019-01-03 23:05 UTC, keerthanamanivannan commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
@gavanderhoorn do you have any suggestions as to what combination of system outputs might work for this?

2019-01-04 09:07 UTC, gavanderhoorn commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
I wouldn't know all of them, but I would at least check those that have to do with e-stop status.

Perhaps @jontje can suggest some others?

2019-01-08 16:40 UTC, keerthanamanivannan commented
@gavanderhoorn alright, so I made some commits and those should take care of points 2, 3 and 4 of the requested changes. 

I had a question about the first one though: [this line](https://github.com/yamokosk/abb/blob/feature/robot_status_message/abb_driver/rapid/ROS_stateServer.mod#L32) says that the broadcast rate is in fact 10 Hz. and we're waiting for this `update_rate` time to send both `joint_states` and `robot_status` messages [here](https://github.com/yamokosk/abb/blob/feature/robot_status_message/abb_driver/rapid/ROS_stateServer.mod#L44-L46). Correct me if I'm wrong. 

And the fifth one, I'm waiting to hear from @jontje for suggestions.

2019-01-08 16:48 UTC, gavanderhoorn commented
> @gavanderhoorn alright, so I made some commits and those should take care of points 2, 3 and 4 of the requested changes.

Great. Thanks for that.

re: pt 3: does `signalRobotActive` in 17c1a5de check for the status of `T_ROB1`?

> I had a question about the first one though: [this line](https://github.com/yamokosk/abb/blob/feature/robot_status_message/abb_driver/rapid/ROS_stateServer.mod#L32) says that the broadcast rate is in fact 10 Hz. and we're waiting for this `update_rate` time to send both `joint_states` and `robot_status` messages [here](https://github.com/yamokosk/abb/blob/feature/robot_status_message/abb_driver/rapid/ROS_stateServer.mod#L44-L46). Correct me if I'm wrong.

You're correct. My comment was meant to say "right now status and joint state msgs are published at the same frequency, which is not necessarily what we want". But they're both at 10 Hz right now. It would be good to decouple those publication rates, but that would be something for another PR.

> And the fifth one, I'm waiting to hear from @jontje for suggestions.

Yes. I would have to check documentation and my notes again to answer that one, so if @jontje could comment on that one it would save me some time.

---

Thanks for updating the PR again.

2019-01-08 17:00 UTC, keerthanamanivannan commented
> re: pt 3: does `signalRobotActive` in [17c1a5d](https://github.com/ros-industrial/abb/commit/17c1a5de357d2526a0739ba049611862b58735f0) check for the status of `T_ROB1`?

I saw [this](http://serioussurvivor.com/wp-content/uploads/2017/03/System-Parameters-3HAC17076-1_revG_en.pdf) doc, pg 253 in the manual itself titled `Mechanical Unit Active` and I believe this System Output would check if T_ROB1 is active or not. Would be great if someone else can confirm this. 

> 
> You're correct. My comment was meant to say "right now status and joint state msgs are published at the same frequency, which is not necessarily what we want". But they're both at 10 Hz right now. It would be good to decouple those publication rates, but that would be something for another PR.

Alright got it, yes, maybe a different PR.
>
> Thanks for updating the PR again.

No problem!

2019-01-08 17:27 UTC, gonzalocasas commented
Minor question: shouldn't we "namespace" the signals that are linked to a specific unit? i.e. `signalRobotActive` and `signalRobotNotMoving`? Otherwise, setting up for a multi-robot system means more departing from standard setup instructions.

2019-01-09 09:50 UTC, jontje commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
Hello,

`errnum = [1, 90]` are reserved for rasing custom errors, while predefined errors can be higher (e.g. `ERR_ROBLIMIT = 1075`).

Anyway, I would use the system output `Execution Error`, and I think it should be enough for determining the `message.in_error` field. This system output is set to `HIGH` when an error has occured that doesn't have any error handler. 

For example:
![system output](https://user-images.githubusercontent.com/16589371/50890566-bf13ac00-13fa-11e9-96f7-39637e5dc368.PNG)

And then check the signal in an IF-statement with `DOutput(signalExecutionError) = HIGH`

2019-01-09 17:12 UTC, keerthanamanivannan commented
> Minor question: shouldn't we "namespace" the signals that are linked to a specific unit? i.e. `signalRobotActive` and `signalRobotNotMoving`? Otherwise, setting up for a multi-robot system means more departing from standard setup instructions.

Good point, and if I had to do this, do you know how I would go about implementing this? 
@gavanderhoorn @jontje any ideas?

@jontje I see a "Assigned to Device" option when I'm creating a Signal in the Robot Controller. But it's showing up empty. Would that be of any help to this task at all?
![capture 3](https://user-images.githubusercontent.com/15019704/50916394-ac03da80-1400-11e9-9432-268f6f428222.PNG)

2019-01-09 17:14 UTC, keerthanamanivannan commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
@jontje this was well explained, thank you! 
@gavanderhoorn I made a commit with this change. I updated the documentation too. Please review it.

2019-01-09 17:49 UTC, gavanderhoorn commented
@keerthanamanivannan: could you please *rebase* your PR on-top of current `kinetic-devel`? Travis refuses to run CI for this PR. I'm not sure whether that is because of the conflicts, but they'll need to be resolved in any case.

2019-01-09 19:08 UTC, gavanderhoorn commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
@keerthanamanivannan: b97cbcbe seems to remove the bit where the code retrieves the current error and initialises the `message.error_code` field with it. Was that intentional?

That field should be set to whatever the current error code is when the system is in an error mode.

2019-01-09 20:18 UTC, keerthanamanivannan commented on abb_driver/rapid/ROS_stateServer.mod
> +    if (message.error_code >= 1) AND (message.error_code <= 90) THEN
@gavanderhoorn ahh I see. Sorry. I've fixed it.

2019-01-09 20:53 UTC, keerthanamanivannan commented
@gavanderhoorn Please review. Thanks!

2019-01-10 09:42 UTC, jontje commented
> Good point, and if I had to do this, do you know how I would go about implementing this?
> @gavanderhoorn @jontje any ideas?

When I have multiple mechanical units in a system then I usually append the unit names as a prefix.
For example using "ROB_X" like this: ROB_1_signal_name, ROB_2_signal_name, etc...

I would also choose to create a RobotWare Add-In that inspects the robot system during installation, and automatically loads the necessary configurations and RAPID modules. However, this would probably require quite a bit of effort if you are not familiar with creating such Add-Ins.

> @jontje I see a "Assigned to Device" option when I'm creating a Signal in the Robot Controller. But it's showing up empty. Would that be of any help to this task at all?

The "Assigned to Device" field is only required when connecting the signal to a physical IO-device. When the field is left empty, then the signal will only be virtual. So it will not be of any help here.

2019-01-10 12:18 UTC, gavanderhoorn commented
> > Good point, and if I had to do this, do you know how I would go about implementing this?
> > @gavanderhoorn @jontje any ideas?
> 
> When I have multiple mechanical units in a system then I usually append the unit names as a prefix.
> For example using "ROB_X" like this: ROB_1_signal_name, ROB_2_signal_name, etc...

hm. That would need changes to the code when deploying on systems with multiple mechanicle units.

@jontje: there is no way to "scope" these signal declarations that would make it less intrusive? Something similar to assigning to a mech unit, as you do with motion tasks?

2019-01-10 13:50 UTC, keerthanamanivannan commented
> hm. That would need changes to the code when deploying on systems with multiple mechanicle units.

Right. I actually work on a multi-robot system. I set each robot separately as a single mechanical unit in ABB Settings. Like, all the robots are named `ROB_1` in the ABB settings, but I launch all the nodes for each robot in its own namespace. Like @gavanderhoorn mentioned in #106.

So I essentially get the info on both the robots like `robot1/robot_status` and `robot2/robot_status`.

2019-01-10 15:44 UTC, jontje commented
> @jontje: there is no way to "scope" these signal declarations that would make it less intrusive? Something similar to assigning to a mech unit, as you do with motion tasks?

Hm, no direct way that I can think of at the moment. Some of the signals are related to the robot controller (e.g. `signalRobotEStop`) and others are related to mechanical units (e.g. `signalRobotNotMoving`). Maybe an idea could be to use cross connections to apply some logic to the signals related to multiple mechanical units.

> Right. I actually work on a multi-robot system. I set each robot separately as a single mechanical unit in ABB Settings. Like, all the robots are named `ROB_1` in the ABB settings, but I launch all the nodes for each robot in its own namespace. Like @gavanderhoorn mentioned in #106.
> 
> So I essentially get the info on all the robots like `robot1/robot_status` and `robot2/robot_status`, and so on.

If I understand correctly, then you work with a multi robot controller system (with one robot each), instead of one robot controller with multiple robots? If so, to make things as generalized as possible then it might be reasonable to set up some namespaces like this:

- `robot_controller1/robot1/robot_status`
- `robot_controller1/robot2/robot_status`
- `robot_controller1/robot3/robot_status`
- `robot_controller2/robot1/robot_status`
- `robot_controller2/robot2/robot_status`
- Etc...

2019-01-10 15:56 UTC, keerthanamanivannan commented
> If I understand correctly, then you work with a multi robot controller system (with one robot each), instead of one robot controller with multiple robots? If so, to make things as generalized as possible then it might be reasonable to set up some namespaces like this:
> 
> * `robot_controller1/robot1/robot_status`
> * `robot_controller1/robot2/robot_status`
> * `robot_controller1/robot3/robot_status`
> * `robot_controller2/robot1/robot_status`
> * `robot_controller2/robot2/robot_status`
> * Etc...

Yes you are correct, I do not have the setup of one robot controller with multiple robots. 
I have four robots and four controllers, with one to one mapping. So my namespacing setup works for me. But I hear you, yeah.

2019-01-14 16:50 UTC, keerthanamanivannan commented
@gavanderhoorn how are we moving forward with this?

2019-02-01 09:17 UTC, gavanderhoorn commented
@keerthanamanivannan: all your commits appear to not be attributed to any email address Github knows about. Is that ok for you? Otherwise I'd recommend you either register the email address with your account, or update the commits.

2019-02-01 16:08 UTC, keerthanamanivannan commented
@gavanderhoorn thank you for bringing that to my attention. I added the email address to my account. :+1:

2019-05-24 13:28 UTC, gavanderhoorn commented
Ok.

So I would like to get this merged in.

Even without explicit "support" for multi-mech-unit setups (or: a nice way to scale/scope the signals in those cases).

I've just added ee970d4 which fixes the `in_motion` field (it didn't take execution status of the motion execution task into account, leading to `in_motion` being `1` while in reality trajectories could not be executed).

I'll wait for Travis to give us a green checkmark and then I'll merge.

2019-05-24 13:46 UTC, gavanderhoorn commented
I've also updated the [install server](http://wiki.ros.org/action/info/abb/Tutorials/InstallServer?action=diff&rev2=25&rev1=21) tutorial on the wiki to mention the new signal.

2019-05-24 14:22 UTC, gonzalocasas commented
> I've also updated the [install server](http://wiki.ros.org/action/info/abb/Tutorials/InstallServer?action=diff&rev2=25&rev1=21) tutorial on the wiki to mention the new signal.

👍 

I actually would prefer to move all those instructions to github, so that they evolve together with the codebase (hence https://github.com/ros-industrial/abb/pull/161), but wiki seems to be the place for it right now.

2019-05-24 14:28 UTC, gavanderhoorn commented
> I actually would prefer to move all those instructions to github, so that they evolve together with the codebase (hence #161), but wiki seems to be the place for it right now.

Yes, that's the still ongoing debate about where ROS pkg documentation should live.

The wiki is still the go-to place for many users. If something is not on the wiki, it doesn't exist for many.

2019-05-24 14:30 UTC, gavanderhoorn commented
I'm going to close this in favour of #168.

As I wrote in the PR there: all the hard work has been done by @yamokosk and @keerthanamanivannan in this PR. I've merely cleaned up and reordered some things.

Thanks @yamokosk and @keerthanamanivannan :+1:.

Apologies for taking so long and all the iterations.

2019-05-24 14:30 UTC, closed without merging