update and unify Readme files
ros-industrial/abb pull request #152
Opened 2018-07-11 16:08 UTC by ipa-nhg

2019-02-02 04:17 UTC, Levi-Armstrong requested changes

2019-02-02 04:17 UTC, Levi-Armstrong commented on README.md
> +The [abb][] repository contains additional packages.
I believe this should remain abb_experimental as it contains addition abb packages.

2019-02-02 04:17 UTC, Levi-Armstrong commented on README.md
> +[abb]: https://github.com/ros-industrial/abb
same as above

2020-04-25 15:50 UTC, gavanderhoorn commented
We're going to this somewhat differently.

Thanks :100: @ipa-nhg for submitting it in any case.

2020-04-25 15:50 UTC, closed without merging